name: "Hello Docker Action"
description: "A simple Docker-based GitHub Action example"
author: "Your Name"
runs:
  using: "docker"
  image: "Dockerfile" # Point to the Dockerfile in the root
  args:
    - ${{ inputs.name }}

inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"

outputs:
  greeting:
    description: "The greeting message"
